//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENG.WMOCodes.Formatters.InfoFormatter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ENG.WMOCodes.Formatters.InfoFormatter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all runways.
        /// </summary>
        internal static string AllRunways {
            get {
                return ResourceManager.GetString("AllRunways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becoming weather.
        /// </summary>
        internal static string BECMG {
            get {
                return ResourceManager.GetString("BECMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broken clouds.
        /// </summary>
        internal static string BKN {
            get {
                return ResourceManager.GetString("BKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blowing.
        /// </summary>
        internal static string BL {
            get {
                return ResourceManager.GetString("BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mist.
        /// </summary>
        internal static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to breaking action.
        /// </summary>
        internal static string BrakingAction {
            get {
                return ResourceManager.GetString("BrakingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to good.
        /// </summary>
        internal static string BrakingActionGood {
            get {
                return ResourceManager.GetString("BrakingActionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        internal static string BrakingActionMedium {
            get {
                return ResourceManager.GetString("BrakingActionMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium to good.
        /// </summary>
        internal static string BrakingActionMediumGood {
            get {
                return ResourceManager.GetString("BrakingActionMediumGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium to poor.
        /// </summary>
        internal static string BrakingActionMediumPoor {
            get {
                return ResourceManager.GetString("BrakingActionMediumPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poor.
        /// </summary>
        internal static string BrakingActionPoor {
            get {
                return ResourceManager.GetString("BrakingActionPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unreliable.
        /// </summary>
        internal static string BrakingActionUnreliable {
            get {
                return ResourceManager.GetString("BrakingActionUnreliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report is cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cumulonimbus.
        /// </summary>
        internal static string CB {
            get {
                return ResourceManager.GetString("CB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clean dry.
        /// </summary>
        internal static string CleanDry {
            get {
                return ResourceManager.GetString("CleanDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string ClosingBracket {
            get {
                return ResourceManager.GetString("ClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compact snow.
        /// </summary>
        internal static string CompactSnow {
            get {
                return ResourceManager.GetString("CompactSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to covered by.
        /// </summary>
        internal static string CoveredBy {
            get {
                return ResourceManager.GetString("CoveredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        internal static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dew point.
        /// </summary>
        internal static string DewPoint {
            get {
                return ResourceManager.GetString("DewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low drifting.
        /// </summary>
        internal static string DR {
            get {
                return ResourceManager.GetString("DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dry snow.
        /// </summary>
        internal static string DrySnow {
            get {
                return ResourceManager.GetString("DrySnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dust storm.
        /// </summary>
        internal static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dust.
        /// </summary>
        internal static string DU {
            get {
                return ResourceManager.GetString("DU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drizzle.
        /// </summary>
        internal static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to funnel cloud.
        /// </summary>
        internal static string FC {
            get {
                return ResourceManager.GetString("FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to few clouds.
        /// </summary>
        internal static string FEW {
            get {
                return ResourceManager.GetString("FEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fog.
        /// </summary>
        internal static string FG {
            get {
                return ResourceManager.GetString("FG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frozent ruts or ridges.
        /// </summary>
        internal static string FrozentRutsRidges {
            get {
                return ResourceManager.GetString("FrozentRutsRidges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        internal static string Ft {
            get {
                return ResourceManager.GetString("Ft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smoke.
        /// </summary>
        internal static string FU {
            get {
                return ResourceManager.GetString("FU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freezing.
        /// </summary>
        internal static string FZ {
            get {
                return ResourceManager.GetString("FZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hail.
        /// </summary>
        internal static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snow pellets.
        /// </summary>
        internal static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy.
        /// </summary>
        internal static string Heavy {
            get {
                return ResourceManager.GetString("Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hPa.
        /// </summary>
        internal static string hPa {
            get {
                return ResourceManager.GetString("hPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haze.
        /// </summary>
        internal static string HZ {
            get {
                return ResourceManager.GetString("HZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ice crystals.
        /// </summary>
        internal static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ice.
        /// </summary>
        internal static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issued at day.
        /// </summary>
        internal static string IssuedAtDay {
            get {
                return ResourceManager.GetString("IssuedAtDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPH.
        /// </summary>
        internal static string KPH {
            get {
                return ResourceManager.GetString("KPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kts.
        /// </summary>
        internal static string KT {
            get {
                return ResourceManager.GetString("KT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 10%.
        /// </summary>
        internal static string LessThan10Percent {
            get {
                return ResourceManager.GetString("LessThan10Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 1 mm.
        /// </summary>
        internal static string LessThan1MM {
            get {
                return ResourceManager.GetString("LessThan1MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 25%.
        /// </summary>
        internal static string LessThan25Percent {
            get {
                return ResourceManager.GetString("LessThan25Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 50%.
        /// </summary>
        internal static string LessThan50Percent {
            get {
                return ResourceManager.GetString("LessThan50Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METAR.
        /// </summary>
        internal static string METAR {
            get {
                return ResourceManager.GetString("METAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPH.
        /// </summary>
        internal static string MIPH {
            get {
                return ResourceManager.GetString("MIPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report is missing.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmHq.
        /// </summary>
        internal static string mmHq {
            get {
                return ResourceManager.GetString("mmHq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than 40 cm.
        /// </summary>
        internal static string MoreThan40CM {
            get {
                return ResourceManager.GetString("MoreThan40CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than 50%.
        /// </summary>
        internal static string MoreThan50Percent {
            get {
                return ResourceManager.GetString("MoreThan50Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPS.
        /// </summary>
        internal static string MPS {
            get {
                return ResourceManager.GetString("MPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northeast.
        /// </summary>
        internal static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to following weather is expected.
        /// </summary>
        internal static string NextWeatherIsExpected {
            get {
                return ResourceManager.GetString("NextWeatherIsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no clouds detected.
        /// </summary>
        internal static string NoCloudsDetected {
            get {
                return ResourceManager.GetString("NoCloudsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No significant change.
        /// </summary>
        internal static string NOSIG {
            get {
                return ResourceManager.GetString("NOSIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no significant clouds.
        /// </summary>
        internal static string NoSignificantCloud {
            get {
                return ResourceManager.GetString("NoSignificantCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depth not reported or rwy closed.
        /// </summary>
        internal static string NotReportedOrClosed {
            get {
                return ResourceManager.GetString("NotReportedOrClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northwest.
        /// </summary>
        internal static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string OpeningBracket {
            get {
                return ResourceManager.GetString("OpeningBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overcast.
        /// </summary>
        internal static string OVC {
            get {
                return ResourceManager.GetString("OVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ice pellets.
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dust or sand whirls.
        /// </summary>
        internal static string PO {
            get {
                return ResourceManager.GetString("PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partial.
        /// </summary>
        internal static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air pressure.
        /// </summary>
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with probability 30%.
        /// </summary>
        internal static string Prob30 {
            get {
                return ResourceManager.GetString("Prob30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with probability 40%.
        /// </summary>
        internal static string Prob40 {
            get {
                return ResourceManager.GetString("Prob40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rain.
        /// </summary>
        internal static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rime or frost.
        /// </summary>
        internal static string RimeOrFrost {
            get {
                return ResourceManager.GetString("RimeOrFrost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runway.
        /// </summary>
        internal static string Runway {
            get {
                return ResourceManager.GetString("Runway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is cleared.
        /// </summary>
        internal static string RunwayIsCleared {
            get {
                return ResourceManager.GetString("RunwayIsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runways&apos; visibility.
        /// </summary>
        internal static string RunwaysVisibilities {
            get {
                return ResourceManager.GetString("RunwaysVisibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decreasing.
        /// </summary>
        internal static string RunwayVisibilityTendency_D {
            get {
                return ResourceManager.GetString("RunwayVisibilityTendency_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no change.
        /// </summary>
        internal static string RunwayVisibilityTendency_N {
            get {
                return ResourceManager.GetString("RunwayVisibilityTendency_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upward.
        /// </summary>
        internal static string RunwayVisibilityTendency_U {
            get {
                return ResourceManager.GetString("RunwayVisibilityTendency_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable between.
        /// </summary>
        internal static string RunwayVisibilityVariableBetween {
            get {
                return ResourceManager.GetString("RunwayVisibilityVariableBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sand.
        /// </summary>
        internal static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scattered clouds.
        /// </summary>
        internal static string SCT {
            get {
                return ResourceManager.GetString("SCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to southeast.
        /// </summary>
        internal static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to southeast.
        /// </summary>
        internal static string SE1 {
            get {
                return ResourceManager.GetString("SE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string Semicolon {
            get {
                return ResourceManager.GetString("Semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snow grains.
        /// </summary>
        internal static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shower.
        /// </summary>
        internal static string SH {
            get {
                return ResourceManager.GetString("SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sky is clear.
        /// </summary>
        internal static string SkyClear {
            get {
                return ResourceManager.GetString("SkyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slush.
        /// </summary>
        internal static string Slush {
            get {
                return ResourceManager.GetString("Slush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snow.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport is closed due to snow.
        /// </summary>
        internal static string SNOCLO {
            get {
                return ResourceManager.GetString("SNOCLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECI.
        /// </summary>
        internal static string SPECI {
            get {
                return ResourceManager.GetString("SPECI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to squalls.
        /// </summary>
        internal static string SQ {
            get {
                return ResourceManager.GetString("SQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sand storm.
        /// </summary>
        internal static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to southwest.
        /// </summary>
        internal static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to southwest.
        /// </summary>
        internal static string SW1 {
            get {
                return ResourceManager.GetString("SW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAF.
        /// </summary>
        internal static string TAF {
            get {
                return ResourceManager.GetString("TAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to towering cumulus.
        /// </summary>
        internal static string TCU {
            get {
                return ResourceManager.GetString("TCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected at .
        /// </summary>
        internal static string TemperatureAtTime {
            get {
                return ResourceManager.GetString("TemperatureAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temporal.
        /// </summary>
        internal static string TEMPO {
            get {
                return ResourceManager.GetString("TEMPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm.
        /// </summary>
        internal static string TS {
            get {
                return ResourceManager.GetString("TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volcanic ash.
        /// </summary>
        internal static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valid from.
        /// </summary>
        internal static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in vicinity.
        /// </summary>
        internal static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical visibility is.
        /// </summary>
        internal static string VerticalVisibility {
            get {
                return ResourceManager.GetString("VerticalVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visibility.
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sky clear..
        /// </summary>
        internal static string VisibilityClear {
            get {
                return ResourceManager.GetString("VisibilityClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string VisibilityFrom {
            get {
                return ResourceManager.GetString("VisibilityFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west.
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wet or/and damp.
        /// </summary>
        internal static string WetDamp {
            get {
                return ResourceManager.GetString("WetDamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wet or wet patches.
        /// </summary>
        internal static string WetOrWetPatches {
            get {
                return ResourceManager.GetString("WetOrWetPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wet snow.
        /// </summary>
        internal static string WetSnow {
            get {
                return ResourceManager.GetString("WetSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wind.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind is calm.
        /// </summary>
        internal static string WindCalm {
            get {
                return ResourceManager.GetString("WindCalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gusting to.
        /// </summary>
        internal static string WindGustingTo {
            get {
                return ResourceManager.GetString("WindGustingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind is varying between.
        /// </summary>
        internal static string WindIsVaryingBetween {
            get {
                return ResourceManager.GetString("WindIsVaryingBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windshear reported at all runways.
        /// </summary>
        internal static string WindshearAllRunways {
            get {
                return ResourceManager.GetString("WindshearAllRunways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windshear at runways.
        /// </summary>
        internal static string WindshearAt {
            get {
                return ResourceManager.GetString("WindshearAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string WindSpeedAt {
            get {
                return ResourceManager.GetString("WindSpeedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        internal static string WindVariable {
            get {
                return ResourceManager.GetString("WindVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string Zulu {
            get {
                return ResourceManager.GetString("Zulu", resourceCulture);
            }
        }
    }
}
