//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENG.WMOCodes.Formatters.ShortInfoFormatter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ENG.WMOCodes.Formatters.ShortInfoFormatter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patches.
        /// </summary>
        internal static string BC {
            get {
                return ResourceManager.GetString("BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broken clouds.
        /// </summary>
        internal static string BKN {
            get {
                return ResourceManager.GetString("BKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blowing.
        /// </summary>
        internal static string BL {
            get {
                return ResourceManager.GetString("BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mist.
        /// </summary>
        internal static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Delimiter_Hour_Minute {
            get {
                return ResourceManager.GetString("Delimiter_Hour_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string Delimiter_ICAO_Date {
            get {
                return ResourceManager.GetString("Delimiter_ICAO_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Dot {
            get {
                return ResourceManager.GetString("Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low drifting.
        /// </summary>
        internal static string DR {
            get {
                return ResourceManager.GetString("DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dust storm.
        /// </summary>
        internal static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dust.
        /// </summary>
        internal static string DU {
            get {
                return ResourceManager.GetString("DU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drizzle.
        /// </summary>
        internal static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to funnel cloud.
        /// </summary>
        internal static string FC {
            get {
                return ResourceManager.GetString("FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to few clouds.
        /// </summary>
        internal static string FEW {
            get {
                return ResourceManager.GetString("FEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fog.
        /// </summary>
        internal static string FG {
            get {
                return ResourceManager.GetString("FG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smoke.
        /// </summary>
        internal static string FU {
            get {
                return ResourceManager.GetString("FU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freezing.
        /// </summary>
        internal static string FZ {
            get {
                return ResourceManager.GetString("FZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hail.
        /// </summary>
        internal static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snow pellets.
        /// </summary>
        internal static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy.
        /// </summary>
        internal static string Heavy {
            get {
                return ResourceManager.GetString("Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hPa.
        /// </summary>
        internal static string HPA {
            get {
                return ResourceManager.GetString("HPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haze.
        /// </summary>
        internal static string HZ {
            get {
                return ResourceManager.GetString("HZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ice crystals.
        /// </summary>
        internal static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kph.
        /// </summary>
        internal static string KPH {
            get {
                return ResourceManager.GetString("KPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knots.
        /// </summary>
        internal static string KT {
            get {
                return ResourceManager.GetString("KT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shallow.
        /// </summary>
        internal static string MI {
            get {
                return ResourceManager.GetString("MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        internal static string MIPH {
            get {
                return ResourceManager.GetString("MIPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmHq.
        /// </summary>
        internal static string MMHQ {
            get {
                return ResourceManager.GetString("MMHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mps.
        /// </summary>
        internal static string MPS {
            get {
                return ResourceManager.GetString("MPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northeast.
        /// </summary>
        internal static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear weather.
        /// </summary>
        internal static string NoClouds {
            get {
                return ResourceManager.GetString("NoClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to northwest.
        /// </summary>
        internal static string NW {
            get {
                return ResourceManager.GetString("NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overcast.
        /// </summary>
        internal static string OVC {
            get {
                return ResourceManager.GetString("OVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ice pellets.
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dust or sand whirls.
        /// </summary>
        internal static string PO {
            get {
                return ResourceManager.GetString("PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partial.
        /// </summary>
        internal static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air pressure .
        /// </summary>
        internal static string PressurePrefix {
            get {
                return ResourceManager.GetString("PressurePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rain.
        /// </summary>
        internal static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sand.
        /// </summary>
        internal static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scattered clouds.
        /// </summary>
        internal static string SCT {
            get {
                return ResourceManager.GetString("SCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to southeast.
        /// </summary>
        internal static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snow grains.
        /// </summary>
        internal static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shower.
        /// </summary>
        internal static string SH {
            get {
                return ResourceManager.GetString("SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snow.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to squalls.
        /// </summary>
        internal static string SQ {
            get {
                return ResourceManager.GetString("SQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sand storm.
        /// </summary>
        internal static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to southwest.
        /// </summary>
        internal static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string TemperaturePostfix {
            get {
                return ResourceManager.GetString("TemperaturePostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temperature.
        /// </summary>
        internal static string TemperaturePrefix {
            get {
                return ResourceManager.GetString("TemperaturePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thunderstorm.
        /// </summary>
        internal static string TS {
            get {
                return ResourceManager.GetString("TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volcanic ash.
        /// </summary>
        internal static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in vicinity.
        /// </summary>
        internal static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west.
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calm.
        /// </summary>
        internal static string WindCalm {
            get {
                return ResourceManager.GetString("WindCalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wind.
        /// </summary>
        internal static string WindPrefix {
            get {
                return ResourceManager.GetString("WindPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string WindSpeedPrefix {
            get {
                return ResourceManager.GetString("WindSpeedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        internal static string WindVariable {
            get {
                return ResourceManager.GetString("WindVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string Zulu {
            get {
                return ResourceManager.GetString("Zulu", resourceCulture);
            }
        }
    }
}
